/** @type {import('tailwindcss').Config} */
// Tailwind CSS Configuration for Fresh Brand Design Token System
// Integrates with new OKLCH-based primitives and semantic tokens (primitives-new.css & semantic-new.css)
// Provides comprehensive accessibility features including colorblind support and enhanced focus states
module.exports = {
  darkMode: ["class"],
  content: [
    './pages/**/*.{ts,tsx}',
    './components/**/*.{ts,tsx}',
    './app/**/*.{ts,tsx}',
    './src/**/*.{ts,tsx}',
  ],
  theme: {
    container: {
      center: true,
      padding: "2rem",
      screens: {
        "2xl": "1400px",
      },
    },
    screens: {
      'xs': '475px',
      'sm': '640px',
      'md': '768px',
      'lg': '1024px',
      'xl': '1280px',
      '2xl': '1536px',
      'tablet': '768px',
      'laptop': '1024px',
      'desktop': '1280px',
    },
    extend: {
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
          50: "hsl(var(--primary-50))",
          100: "hsl(var(--primary-100))",
          400: "hsl(var(--primary-400))",
          600: "hsl(var(--primary-600))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
          hover: "hsl(var(--destructive)) / 0.9",
          active: "hsl(var(--destructive)) / 0.8",
        },
        success: {
          DEFAULT: "hsl(var(--success))",
          foreground: "hsl(var(--success-foreground))",
          hover: "hsl(var(--success)) / 0.9",
        },
        warning: {
          DEFAULT: "hsl(var(--warning))",
          foreground: "hsl(var(--warning-foreground))",
          hover: "hsl(var(--warning)) / 0.9",
        },
        info: {
          DEFAULT: "hsl(var(--info))",
          foreground: "hsl(var(--info-foreground))",
          hover: "hsl(var(--info)) / 0.9",
        },
        demo: {
          DEFAULT: "hsl(var(--demo))",
          foreground: "hsl(var(--demo-foreground))",
          hover: "hsl(var(--demo)) / 0.9",
        },
        "trade-show": {
          DEFAULT: "hsl(var(--trade-show))",
          foreground: "hsl(var(--trade-show-foreground))",
          hover: "hsl(var(--trade-show)) / 0.9",
        },
        "site-visit": {
          DEFAULT: "hsl(var(--site-visit))",
          foreground: "hsl(var(--site-visit-foreground))",
          hover: "hsl(var(--site-visit)) / 0.9",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        sidebar: {
          DEFAULT: "hsl(var(--sidebar-background))",
          foreground: "hsl(var(--sidebar-foreground))",
          primary: "hsl(var(--sidebar-primary))",
          "primary-foreground": "hsl(var(--sidebar-primary-foreground))",
          accent: "hsl(var(--sidebar-accent))",
          "accent-foreground": "hsl(var(--sidebar-accent-foreground))",
          border: "hsl(var(--sidebar-border))",
          ring: "hsl(var(--sidebar-ring))",
        },
        brand: {
          'primary': 'hsl(var(--brand-primary-hsl))',
          'primary-hover': 'hsl(var(--brand-primary-hover-hsl))',
          'primary-focus': 'hsl(var(--brand-primary-focus-hsl))',
          'primary-active': 'hsl(var(--brand-primary-active-hsl))',
          'primary-disabled': 'hsl(var(--brand-primary-disabled-hsl))',
          'primary-light': 'hsl(var(--brand-primary-light-hsl))',
          'primary-subtle': 'hsl(var(--brand-primary-subtle-hsl))',
          'secondary': 'hsl(var(--brand-secondary-hsl))',
          'secondary-hover': 'hsl(var(--brand-secondary-hover-hsl))',
          'secondary-focus': 'hsl(var(--brand-secondary-focus-hsl))',
          'secondary-active': 'hsl(var(--brand-secondary-active-hsl))',
          'secondary-disabled': 'hsl(var(--brand-secondary-disabled-hsl))',
          'secondary-light': 'hsl(var(--brand-secondary-light-hsl))',
          'secondary-subtle': 'hsl(var(--brand-secondary-subtle-hsl))',
          'accent': 'hsl(var(--brand-accent-hsl))',
          'accent-hover': 'hsl(var(--brand-accent-hover-hsl))',
          'accent-focus': 'hsl(var(--brand-accent-focus-hsl))',
          'accent-active': 'hsl(var(--brand-accent-active-hsl))',
          'accent-disabled': 'hsl(var(--brand-accent-disabled-hsl))',
          'accent-light': 'hsl(var(--brand-accent-light-hsl))',
          'accent-subtle': 'hsl(var(--brand-accent-subtle-hsl))',
        },
        semantic: {
          'success': 'hsl(var(--semantic-success-hsl))',
          'success-hover': 'hsl(var(--semantic-success-hover-hsl))',
          'success-focus': 'hsl(var(--semantic-success-focus-hsl))',
          'success-active': 'hsl(var(--semantic-success-active-hsl))',
          'success-disabled': 'hsl(var(--semantic-success-disabled-hsl))',
          'success-light': 'hsl(var(--semantic-success-light-hsl))',
          'success-subtle': 'hsl(var(--semantic-success-subtle-hsl))',
          'warning': 'hsl(var(--semantic-warning-hsl))',
          'warning-hover': 'hsl(var(--semantic-warning-hover-hsl))',
          'warning-focus': 'hsl(var(--semantic-warning-focus-hsl))',
          'warning-active': 'hsl(var(--semantic-warning-active-hsl))',
          'warning-disabled': 'hsl(var(--semantic-warning-disabled-hsl))',
          'warning-light': 'hsl(var(--semantic-warning-light-hsl))',
          'warning-subtle': 'hsl(var(--semantic-warning-subtle-hsl))',
          'error': 'hsl(var(--semantic-error-hsl))',
          'error-hover': 'hsl(var(--semantic-error-hover-hsl))',
          'error-focus': 'hsl(var(--semantic-error-focus-hsl))',
          'error-active': 'hsl(var(--semantic-error-active-hsl))',
          'error-disabled': 'hsl(var(--semantic-error-disabled-hsl))',
          'error-light': 'hsl(var(--semantic-error-light-hsl))',
          'error-subtle': 'hsl(var(--semantic-error-subtle-hsl))',
          'info': 'hsl(var(--semantic-info-hsl))',
          'info-hover': 'hsl(var(--semantic-info-hover-hsl))',
          'info-focus': 'hsl(var(--semantic-info-focus-hsl))',
          'info-active': 'hsl(var(--semantic-info-active-hsl))',
          'info-disabled': 'hsl(var(--semantic-info-disabled-hsl))',
          'info-light': 'hsl(var(--semantic-info-light-hsl))',
          'info-subtle': 'hsl(var(--semantic-info-subtle-hsl))',
        },
        priority: {
          'critical': 'hsl(var(--priority-critical))',
          'critical-foreground': 'hsl(var(--priority-critical-foreground))',
          'high': 'hsl(var(--priority-high))',
          'high-foreground': 'hsl(var(--priority-high-foreground))',
          'medium': 'hsl(var(--priority-medium))',
          'medium-foreground': 'hsl(var(--priority-medium-foreground))',
          'normal': 'hsl(var(--priority-normal))',
          'normal-foreground': 'hsl(var(--priority-normal-foreground))',
          'low': 'hsl(var(--priority-low))',
          'low-foreground': 'hsl(var(--priority-low-foreground))',
          // Legacy mappings for backward compatibility
          'a-plus': 'hsl(var(--priority-a-plus))',
          'a-plus-foreground': 'hsl(var(--priority-a-plus-foreground))',
          'a': 'hsl(var(--priority-a))',
          'a-foreground': 'hsl(var(--priority-a-foreground))',
          'b': 'hsl(var(--priority-b))',
          'b-foreground': 'hsl(var(--priority-b-foreground))',
          'c': 'hsl(var(--priority-c))',
          'c-foreground': 'hsl(var(--priority-c-foreground))',
          'd': 'hsl(var(--priority-d))',
          'd-foreground': 'hsl(var(--priority-d-foreground))',
        },
        organization: {
          'customer': 'hsl(var(--org-customer))',
          'customer-foreground': 'hsl(var(--org-customer-foreground))',
          'distributor': 'hsl(var(--org-distributor))',
          'distributor-foreground': 'hsl(var(--org-distributor-foreground))',
          'principal': 'hsl(var(--org-principal))',
          'principal-foreground': 'hsl(var(--org-principal-foreground))',
          'supplier': 'hsl(var(--org-supplier))',
          'supplier-foreground': 'hsl(var(--org-supplier-foreground))',
          'vendor': 'hsl(var(--org-vendor))',
          'vendor-foreground': 'hsl(var(--org-vendor-foreground))',
          'prospect': 'hsl(var(--org-prospect))',
          'prospect-foreground': 'hsl(var(--org-prospect-foreground))',
          'unknown': 'hsl(var(--org-unknown))',
          'unknown-foreground': 'hsl(var(--org-unknown-foreground))',
        },
        segment: {
          'restaurant': 'hsl(var(--segment-restaurant))',
          'restaurant-foreground': 'hsl(var(--segment-restaurant-foreground))',
          'healthcare': 'hsl(var(--segment-healthcare))',
          'healthcare-foreground': 'hsl(var(--segment-healthcare-foreground))',
          'education': 'hsl(var(--segment-education))',
          'education-foreground': 'hsl(var(--segment-education-foreground))',
        },
        // Enhanced Grayscale System - New Token Integration
        gray: {
          50: 'hsl(var(--gray-50-hsl))',
          100: 'hsl(var(--gray-100-hsl))',
          200: 'hsl(var(--gray-200-hsl))',
          300: 'hsl(var(--gray-300-hsl))',
          400: 'hsl(var(--gray-400-hsl))',
          500: 'hsl(var(--gray-500-hsl))',
          600: 'hsl(var(--gray-600-hsl))',
          700: 'hsl(var(--gray-700-hsl))',
          800: 'hsl(var(--gray-800-hsl))',
          900: 'hsl(var(--gray-900-hsl))',
          950: 'hsl(var(--gray-950-hsl))',
        },
        // CRM Workflow States - New Implementation
        data: {
          'valid': 'hsl(var(--data-valid))',
          'valid-foreground': 'hsl(var(--data-valid-foreground))',
          'invalid': 'hsl(var(--data-invalid))',
          'invalid-foreground': 'hsl(var(--data-invalid-foreground))',
          'pending': 'hsl(var(--data-pending))',
          'pending-foreground': 'hsl(var(--data-pending-foreground))',
        },
        bulk: {
          'selected': 'hsl(var(--bulk-selected))',
          'selected-foreground': 'hsl(var(--bulk-selected-foreground))',
          'processing': 'hsl(var(--bulk-processing))',
          'processing-foreground': 'hsl(var(--bulk-processing-foreground))',
        },
        import: {
          'in-progress': 'hsl(var(--import-in-progress))',
          'in-progress-foreground': 'hsl(var(--import-in-progress-foreground))',
          'complete': 'hsl(var(--import-complete))',
          'complete-foreground': 'hsl(var(--import-complete-foreground))',
          'failed': 'hsl(var(--import-failed))',
          'failed-foreground': 'hsl(var(--import-failed-foreground))',
        },
        sync: {
          'synced': 'hsl(var(--sync-synced))',
          'synced-foreground': 'hsl(var(--sync-synced-foreground))',
          'pending': 'hsl(var(--sync-pending))',
          'pending-foreground': 'hsl(var(--sync-pending-foreground))',
          'error': 'hsl(var(--sync-error))',
          'error-foreground': 'hsl(var(--sync-error-foreground))',
        },
        // Enhanced Focus System - New Accessibility Tokens
        focus: {
          'ring': 'hsl(var(--brand-primary-hsl))',
          'ring-destructive': 'hsl(var(--focus-ring-destructive-hsl))',
          'ring-secondary': 'hsl(var(--focus-ring-secondary-hsl))',
          'ring-accent': 'hsl(var(--focus-ring-accent-hsl))',
          'ring-success': 'hsl(var(--semantic-success-hsl))',
          'ring-warning': 'hsl(var(--semantic-warning-hsl))',
          'ring-info': 'hsl(var(--semantic-info-hsl))',
        },
        // Colorblind-Safe Color System - New Accessibility Features
        colorblind: {
          'success-bg': 'hsl(var(--cb-success-bg-hsl))',
          'success-text': 'hsl(var(--cb-success-text-hsl))',
          'success-border': 'hsl(var(--cb-success-border-hsl))',
          'warning-bg': 'hsl(var(--cb-warning-bg-hsl))',
          'warning-text': 'hsl(var(--cb-warning-text-hsl))',
          'warning-border': 'hsl(var(--cb-warning-border-hsl))',
          'danger-bg': 'hsl(var(--cb-danger-bg-hsl))',
          'danger-text': 'hsl(var(--cb-danger-text-hsl))',
          'danger-border': 'hsl(var(--cb-danger-border-hsl))',
          'info-bg': 'hsl(var(--cb-info-bg-hsl))',
          'info-text': 'hsl(var(--cb-info-text-hsl))',
          'info-border': 'hsl(var(--cb-info-border-hsl))',
        },
      },
      fontFamily: {
        'nunito': ['Nunito', 'system-ui', 'sans-serif'],
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      height: {
        'header': 'var(--header-height)',
        'chart': 'var(--chart-height)',
        'chart-sm': 'var(--chart-height-sm)',
        'chart-lg': 'var(--chart-height-lg)',
        'activity-feed': 'var(--activity-feed-height)',
        'kanban-content': 'var(--kanban-content-height)',
      },
      maxHeight: {
        'dialog': 'var(--dialog-max-height)',
        'activity-feed': 'var(--activity-feed-height)',
        'kanban-content': 'var(--kanban-content-height)',
      },
      minWidth: {
        'kanban-column': 'var(--kanban-column-min-width)',
        'search-sm': 'var(--search-width-sm)',
        'search-lg': 'var(--search-width-lg)',
      },
      width: {
        'search-sm': 'var(--search-width-sm)',
        'search-lg': 'var(--search-width-lg)',
        'filter-sm': 'var(--filter-width-sm)',
        'filter-md': 'var(--filter-width-md)',
      },
      keyframes: {
        "accordion-down": {
          from: { height: 0 },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: 0 },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
}