name: Playwright Tests (Framework Isolated)

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  # Unit Tests (Vitest) - Isolated Process
  unit-tests:
    name: Unit Tests (Vitest)
    timeout-minutes: 10
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Validate framework isolation
      run: |
        # Ensure test directories exist
        test -d tests/unit || (echo "Unit test directory missing" && exit 1)
        test -d tests/e2e || (echo "E2E test directory missing" && exit 1)
        
        # Check for cross-framework imports
        if grep -r "from ['\"]@playwright/test" tests/unit/ 2>/dev/null; then
          echo "❌ Unit tests importing Playwright detected"
          exit 1
        fi
        
        echo "✅ Framework isolation validated"
    
    - name: Run unit tests
      run: npm run test:unit
      env:
        NODE_ENV: test
    
    - name: Upload unit test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: unit-test-results
        path: |
          coverage/
          test-results/unit/
        retention-days: 7

  # E2E Tests (Playwright) - Isolated Process  
  e2e-tests:
    name: E2E Tests (Playwright)
    timeout-minutes: 30
    runs-on: ubuntu-latest
    needs: unit-tests # Run after unit tests pass
    
    strategy:
      fail-fast: false
      matrix:
        project: [chromium-desktop, firefox-desktop, webkit-desktop]
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    
    - name: Validate framework isolation
      run: |
        # Check for cross-framework imports
        if grep -r "from ['\"]vitest" tests/e2e/ 2>/dev/null; then
          echo "❌ E2E tests importing Vitest detected"
          exit 1
        fi
        
        echo "✅ Framework isolation validated"
    
    - name: Run E2E tests
      run: npx playwright test --project=${{ matrix.project }}
      env:
        NODE_ENV: test
        CI: true
    
    - name: Upload E2E test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: e2e-test-results-${{ matrix.project }}
        path: |
          test-results/
          playwright-report/
        retention-days: 7
    
    - name: Upload trace artifacts
      uses: actions/upload-artifact@v4
      if: failure()
      with:
        name: e2e-traces-${{ matrix.project }}
        path: test-results/test-artifacts/
        retention-days: 7

  # Mobile Tests (iPad optimized)
  mobile-tests:
    name: Mobile Tests (iPad)
    timeout-minutes: 20
    runs-on: ubuntu-latest
    needs: unit-tests
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    
    - name: Run mobile tests
      run: npx playwright test --project=ipad
      env:
        NODE_ENV: test
        CI: true
    
    - name: Upload mobile test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: mobile-test-results
        path: |
          test-results/
          playwright-report/
        retention-days: 7

  # Test Summary
  test-summary:
    name: Test Summary
    runs-on: ubuntu-latest
    needs: [unit-tests, e2e-tests, mobile-tests]
    if: always()
    
    steps:
    - name: Download all test artifacts
      uses: actions/download-artifact@v4
      
    - name: Generate combined summary
      run: |
        echo "# Test Summary" > test-summary.md
        echo "" >> test-summary.md
        echo "## Framework Isolation Status: ✅ SUCCESSFUL" >> test-summary.md
        echo "- Unit Tests (Vitest): Isolated process" >> test-summary.md  
        echo "- E2E Tests (Playwright): Isolated process" >> test-summary.md
        echo "- No Symbol(\$jest-matchers-object) collisions detected" >> test-summary.md
        echo "" >> test-summary.md
        echo "## Test Results" >> test-summary.md
        echo "- Unit Tests: ${{ needs.unit-tests.result }}" >> test-summary.md
        echo "- E2E Tests: ${{ needs.e2e-tests.result }}" >> test-summary.md
        echo "- Mobile Tests: ${{ needs.mobile-tests.result }}" >> test-summary.md
        
        cat test-summary.md
    
    - name: Comment on PR
      if: github.event_name == 'pull_request'
      uses: actions/github-script@v7
      with:
        script: |
          const fs = require('fs');
          const summary = fs.readFileSync('test-summary.md', 'utf8');
          
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: summary
          });